version: "3.9"

services:
  api:
    container_name: api
    restart: always
    networks:
      - video-call
      - mailer
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env

  mailer:
    restart: always
    networks:
      - mailer
    build:
      context: ./mailer
      dockerfile: Dockerfile
    env_file:
      - .env

  mongo:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    restart: always
    networks:
      - video-call
    volumes:
      - mongo-data:/data/db
      - ./mongodb/config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://mongo:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: video-call

networks:
  video-call:
    driver: bridge
  mailer:
    driver: bridge

volumes:
  mongo-data:
    driver: local
