FROM node:20.9-alpine

WORKDIR /app

COPY ./package.json ./
COPY ./tsconfig.json ./

RUN npm cache clean --force \
    && rm -rf node_modules \
    && npm install

COPY  ./ ./

EXPOSE 8082

CMD [ "npm", "run", "dev" ]
